export const GENRES = 'GENRES';
export const MOVIES_BY_GENRE = 'MOVIES_BY_GENRE';
export const MOVIE_STREAMING_SERVICES = 'MOVIE_STREAMING_SERVICES';
export const MOVIE_INDEX = 'MOVIE_INDEX';
export const MOST_POPULAR_MOVIES = 'MOST_POPULAR_MOVIES';
