export const SET_ROOM_STATE = 'SET_ROOM_STATE';
export const SET_ROOM_SIZE = 'SET_ROOM_SIZE';
export const MOVIE_SWIPE = 'MOVIE_SWIPE';
// export const SET_ROOM_SIZE_LISTENER = 'SET_ROOM_SIZE_LISTENER';
