export const SET_ROOM_STATE = 'SET_ROOM_STATE'
export const SET_ROOM_SIZE = 'SET_ROOM_SIZE'
export const MATCH_FOUND = 'MATCH_FOUND'
export const SET_MOVIE_PAYLOAD = 'SET_MOVIE_PAYLOAD'
// export const SET_ROOM_SIZE_LISTENER = 'SET_ROOM_SIZE_LISTENER';
