export const SET_ROOM_STATE = 'SET_ROOM_STATE'
export const SET_ROOM_SIZE = 'SET_ROOM_SIZE'
export const SET_MOVIE_PAYLOAD = 'SET_MOVIE_PAYLOAD'
export const REMOVE_LIKED_MOVIE = 'REMOVE_LIKED_MOVIE'
export const RESET_ROOM = 'RESET_ROOM'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'

export const EXPERIENCES = {
  SOLO: 'SOLO',
  GROUP: 'GROUP',
}
